### ISSUE TITLE
`FixedPoint::integer` is by value, `Generic::integer` is not

### ISSUE THREAD

**Issue by korken89** [FluenTech/embedded-time#107]
Hi @PTaylor-us 

I think this was an oversight when the integer API was changed.
Now the API has bifurcated, should I fix a PR and maybe we should release a new version?

**Comment by PTaylor-us** [comment]
Absolutely correct. I didn't think to change `Generic::integer`. I'll take a look at this a little later today. Thanks for the heads-up.

**Comment by PTaylor-us** [comment]
Fixed (589acd79d296e704d8a0576a45877db3607f3792)

**Comment by korken89** [comment]
Hi, the fix seems to not have made it to master?

**Comment by PTaylor-us** [comment]
merged to master May 30
