### ISSUE TITLE
New release with the latest update and fixes

### ISSUE THREAD

**Issue by korken89** [FluenTech/embedded-time#108]
Hi @PTaylor-us,

How are your thoughts on a new release?
With `0.11` the library is a bit in limbo with the interfaces, so should we perhaps release `0.12` ASAP?

BR Emil

**Comment by PTaylor-us** [comment]
Good idea. I'll do that today.

**Comment by korken89** [comment]
I saw that it was released, thanks!

It seems like the release was not made from the `master` branch? Could you have a look at merging from `develop` into `master` the changes that were released?

**Comment by PTaylor-us** [comment]
It should be now. I did forget to push to master until the next day.

**Comment by korken89** [comment]
Thanks!
