### ISSUE TITLE
Fallibility of `Clock` methods for I2C RTC device driver implementations

### ISSUE THREAD

**Issue by eldruin** [FluenTech/embedded-time#25]
First of all, thank you for taking the time to develop embedded-time!

I had a quick look at if implementing `Clock` for I2C RTC devices since I [wrote](https://github.com/eldruin/ds1307-rs) [a few](https://github.com/eldruin/ds323x-rs) [drivers](https://github.com/eldruin/mcp794xx-rs) but at the moment this seems not possible due to fallibility of the methods.

As any interaction over I2C can fail for several reasons (there is undergoing discussion about this at https://github.com/rust-embedded/embedded-hal/issues/229), the methods must provide a way to return an error.
This includes `Clock::now()` and by extension also `Clock::delay()`.

For embedded-time I guess an associated `Error` type would make sense so that any implementation can have its own error definitions.

However, this would make sense if `embedded_time::Clock` implementations on top or I2C RTC device drivers are desired and _may_ be unnecessary for HAL (timer/counter-based) implementations. This would be a project focus question.

**Comment by PTaylor-us** [comment]
I hadn't considered external clock sources at all. Thank you so much for bringing this to my attention. I will take a look at the discussion you linked to. Tentatively, it does seem as though an associated `Error` type might make the most sense (probably `Infallible` for on-chip peripheral `Clock` impls).
