### ISSUE TITLE
error[E0284]: type annotations needed

### ISSUE THREAD

**Issue by Luis-Hebendanz** [FluenTech/embedded-time#81]
![1604247391_grim](https://user-images.githubusercontent.com/22085373/97808234-07522d00-1c66-11eb-8974-3ad7d07655f5.png)

```
$ rustup show
active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.49.0-nightly (91a79fb29 2020-10-07)
```

**Comment by fry** [comment]
Seconding that, compiles fine on nightly-2020-10-05 for me.

**Comment by twitchyliquid64** [comment]
Ditto - any chance we could release a new version with this fix?

**Comment by PTaylor-us** [comment]
I'll do this in the next day or two. Sorry for the delay.
