### ISSUE TITLE
Generically take any duration?

### ISSUE THREAD

**Issue by korken89** [FluenTech/embedded-time#92]
Hi, I have issues with getting the following code to compile as I am unable to get the correct traits needed.
Could you assist here @PTaylor-us ?

```rust
pub fn spawn_after<D: embedded_time::duration::Duration>(duration: D) -> Result<(), ()> {
    let instant = <MyClock as rtic::Monotonic>::now(); // Return an Instant<MyClock>

    // This addition seems to be the issue
    spawn_at(instant + duration, #(,#untupled)*)
}
```

**Comment by korken89** [comment]
We found the correct traits that were needed eventually. Would there be any way to make this simpler?

Solution:

```rust
pub fn spawn_after<D>(duration: D) -> Result<(), ()>
    where D: embedded_time::duration::Duration + embedded_time::fixed_point::FixedPoint,
       D::T: Into<<MyClock as embedded_time::Clock>::T>,
{
    let instant = <MyClock as rtic::Monotonic>::now();

    spawn_at(instant + duration, #(,#untupled)*)
}
```

**Comment by wbuck** [comment]
I did have a similar request.
Would it be possible to export the `TimeInt` trait?

It would be beneficial when trying to create a custom type, i.e `Rpm`.

**Comment by PTaylor-us** [comment]
I want to allow easy generic usage of any `Duration`/`Rate` (including Generic) with only a `embedded_time::Duration` where clause. I'm assuming this is not possible because the `Add` implementation for Instant requires that the Duration impl `FixedPoint`. This will probably take me some time to figure out unless anyone can help me out. I feel like there's a trait pattern that is missing.

**Comment by PTaylor-us** [comment]
## Proposed Solution 

- move associated const SCALING_FACTOR out of FixedPoint
- move FixedPoint into Duration 

This should allow this (eliminate the need to bind `FixedPoint`: 
```
pub fn spawn_after<D>(duration: D) -> Result<(), ()>
    where D: embedded_time::duration::Duration,
       D::T: Into<<MyClock as embedded_time::Clock>::T>,
{
    let instant = <MyClock as rtic::Monotonic>::now();

    spawn_at(instant + duration, #(,#untupled)*)
}
```

@korken89 I'm not seeing a good way to eliminate the need for the `Into` binding, though.

**Comment by PTaylor-us** [comment]
This may not work fully. I wanted to move the const SCALING_FACTOR out of FixedPoint so Generic could also implement FixedPoint, but obviously, the scaling factor of the FixedPoint number must be accessible by the FixedPoint concrete type.

**Comment by PTaylor-us** [comment]
Current plan is to bind FixedPoint to Duration and Rate. Then I will remove the Duration and Rate implementations for the Generic versions.

**Comment by korken89** [comment]
Sounds interesting, I'll be lurking. :)

**Comment by PTaylor-us** [comment]
Completed for v0.13.0 release PR
