### ISSUE TITLE
Proposal: Only implement `Extension` traits for u32 for ergonomy

### ISSUE THREAD

**Issue by korken89** [FluenTech/embedded-time#95]
For the sake of ergonomic use I'd recommend that the `Extension` traits only be implemented for `u32` 
so that the expected operation works. Such as `3.seconds()`, `44.milliseconds()` etc.
Getting rid of the must have `_u32`/`_u64` or similar.

If one wants to be specific type can still use the types directly: `Seconds(1_u64)`.

What are your thoughts on this @PTaylor-us ?

**Comment by PTaylor-us** [comment]
I agree it would be much nicer to use. I struggled with this for a long time trying to make u32 the default, but I couldn't get that to work. I guess, that works for me since 64-bit can still be used, just not with the extensions.

**Comment by korken89** [comment]
I made a branch testing this and all worked fine.

I'll prepare a PR after some cleaning!
